#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# (c) ACE 

import os

class Config(object):
    # get a token from @BotFather
    pass
    """
    BOT_TOKEN = os.environ.get("BOT_TOKEN", "7261065849:AAGjf_57RekgfZ2A2U29oIcRwVtZFquXu-4")
    API_ID = int(os.environ["API_ID", 28700344]
    API_HASH = os.environ["API_HASH", "7ef39c8ff60df33dc5e55d418fa8b636"]
    AUTH_USERS = "7131041669"""
# jisko bhi is repo ko deploy karne me error aa raha ho ( https://t.me/Stubborn1223 ) ye mere TG ka id ha message karke iska screen shot send kar dena me error solve kar dunga. 
